name: Arqueologica 2.0 2016
markdown: redcarpet
highlighter: pygments
gems: ['jekyll-sass']
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css"]
