name: I Congreso Nacional sobre Documentación y Arqueometría del Arte Rupestre
markdown: redcarpet
highlighter: pygments
gems: ['jekyll-sass']
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
